project:
  type: website
  output-dir: docs

website:
  title: "GeoMusketeer"
  navbar:
    left:
      - href: project.qmd
        text: Project Proposal
      - href: methodology.qmd
        text: Methodology
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

