project:
  type: website
  output-dir: docs

website:
  title: "GeoMusketeer"
  navbar:
    left:
      - href: project.qmd
        text: Project Proposal
      - text: "Methodology"
        menu:
        - datacollection.qmd
        - datapreparation.qmd
        - chloropleth.qmd
        - accessibility.qmd
      - href: results.qmd
        text: Restuls & Discussion
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

