project:
  type: website
  output-dir: docs

website:
  title: "GeoMusketeer"
  navbar:
    left:
      - href: project.qmd
        text: Project Proposal
      - text: "Methodology"
        menu:
        - datacollection.qmd
        - datapreparation.qmd
        - potential_sites.qmd
        - accessibility.qmd
      - href: results.qmd
        text: Results & Discussion
      - href: lessons.qmd
        text: Lessons Learnt
#      - text: "Webmaps"
#        menu:
#       - text: "Potential Sites For Future Flood Events"
#         href: /Potential_Sites_For_Future_Flood_Events/index.html
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

