project:
  type: website
  output-dir: docs

website:
  title: "GeoMusketeer"
  navbar:
    left:
      - href: project.qmd
        text: Project Proposal
      - text: "Methodology"
        menu:
        - datacollection.qmd
        - datapreparation.qmd
        - potential_sites.qmd
        - accessibility.qmd
      - href: results.qmd
        text: Results & Discussion
      - href: lessons.qmd
        text: Lessons Learnt
      - href: poster.qmd
        text: Poster
      - href: about.qmd
        text: About

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

