project:
  type: website
  output-dir: docs

website:
  title: "GeoMusketeer"
  navbar:
    left:
      - href: proposal.qmd
        text: Project Proposal
    right:
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

