---
title: "Conclusion"
editor: visual
---

To conclude, the current level of accessibility to emergency centres and healthcare facilities in Derna City are notably insufficient. The majority of residential towns are located more than 2.5 km away from the nearest shelter and falls outside the buffer service area, making it inaccessible for residents. It can be suggested that most of Derna City's residents are at a lower risk during such flooding events. However, with the worsening floods in Libya coupled with the lack of shelters, these areas will become increasingly vulnerable over time.

Moreover, the current flooding situation is aggravated because many existing shelters are within the flooded area, restricting access. This means that if these shelters are flooded, it reduces the number of evacuation options for residents within the flooded area. Additionally, it will increase the time taken for residents to reach a safety area. Therefore, the need to have additional emergency shelters to mitigate potential disasters in the future is essential.

In the long term, we have a few recommendations to better prepare Derna City for future flood disasters. Firstly, it is recommended for the government to increase the quantity of emergency centres. It would be advisable to construct these centres at locations with elevated and slope terrain, with a preference for higher elevation and ensuring accessibility to major residential areas. This is essential in minimising vulnerability during unprecedented flood events when access to emergency services is limited. In general, it will allow for greater capacity, which means more displaced people will have a temporary home. It will also help to distribute human flow better as people have more options on which shelter to go to.

Secondly, on top of building centres at places with elevated and slope terrain, it is crucial to ensure that these locations are accessible to food and drinkable water. This is to ensure that residents are able to survive at these centres until they are able to move back to their homes.

Thirdly, the adoption of advanced technologies is crucial. Implementing predictive technologies for disaster events will enhance residents' preparedness. Additionally, investing in robust warning systems will significantly reduce vulnerability. People will have ample time to evacuate their houses and move to a shelter, reducing deaths, injuries and likelihood of overcrowding at the same few shelters. Flood prediction systems can also be explored to predict the magnitude of the incoming flood and inform people on which shelters they should go to.

