---
title: "Project Proposal"
editor: visual
---

## Project Motivation

Libya has been facing a serious crisis of being plagued by flood disasters in recent years due to climate change. This had led to life threatening consequences of death and destruction in the country. For instance, the collapse of Derna dam in 2023 caused thousands of deaths and irreversible damage to infrastructure, devastating the country socially and economically. As a result, the government has decided to deploy mitigation measures to prepare for future disasters and assist in recovery and relief. 

Through this project, we want to find out the current state of preparedness in Derna city by mapping out the accessibility to emergency centres and medical services to aid in disaster relief. We hope to be able to provide meaningful insights on mitigating urban flood disasters in Derna city so as to provide actionable suggestions for future disaster management planning.

## Project objectives

Our objective is to analyse the accessibility to emergency evacuation centres and medical services in the event of a future flood.

We plan to conduct this by comparing the locations of emergency and medical centres and their accessibility to residential which are densely populated, and analysing whether there is a sufficient number of emergency and medical centres in Derna city. 

**Our 2 research questions are as follows:**

1.  Are there enough emergency and medical centres in the area to meet demands in Derna city?

2.  Which areas have less emergency and medical centres and are less accessible which may potentially affect the efficiency of disaster relief?

## Scope of work

The project will comprise of, but not limited to the followings steps:

-   Selection of project areas of flooded areas in Derna city in the years flood disasters occurred.

-   Collection, extraction, integration, transformation and wrangling of data of emergency and medical centres in Derna city.

-   Designing and building GIS model and database to map the accessibility of emergency and medical centres in Derna city.

-   Preparing report of findings.

-   Preparing site suitability analysis report including detailed discussion of the analysing method used.

-   Preparing poster and project webpage.
